"""Render docs/measurements-hackathon/raised_items.yaml as a Markdown page.

Usage:
    uv run python scripts/render_raised_items.py          # write the page
    uv run python scripts/render_raised_items.py --check  # exit 1 if the page is stale
"""

import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "measurements-hackathon" / "raised_items.yaml"
TARGET = ROOT / "docs" / "measurements-hackathon" / "raised-items.md"

DISPOSITIONS = {
    "in_schema": "Handled in measurements.yaml",
    "known_gap": "Known gap, shown by a problem example",
    "open_question": "Open question for the group",
    "deferred": "Deferred to a later module or working group",
    "out_of_scope": "Not a schema matter",
}

SOURCES = {
    "chat": "Zoom chat",
    "drawing": "brainstorm drawing",
    "notes": "Hackathon Notes",
    "slides": "intro slides",
    "recap": "DM notes 10/07",
    "reportout": "Report Out tab",
    "issue4": "issue 4",
    "review": "first-pass review",
}


def cell(text: str) -> str:
    """Escape a value for a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(items: list[dict]) -> str:
    """Return the Markdown page for the raised items."""
    by_disposition = Counter(item["disposition"] for item in items)
    by_source = Counter(item["source"] for item in items)
    lines = [
        "# Raised items: BRIDGE Measurements hackathon, 2026-09-30",
        "",
        "<!-- Generated by scripts/render_raised_items.py from raised_items.yaml. Edit the YAML, not this page. -->",
        "",
        f"{len(items)} items were raised in the hackathon notes, Zoom chat, brainstorm drawing, "
        "intro slides, Report Out tab, issue 4 and the 10/07 DM notes. Each one is listed below "
        "with where it went in `measurements.yaml` 0.3.0. The synthesis is in "
        "[../measurements-hackathon-2026-09-30.md](../measurements-hackathon-2026-09-30.md).",
        "",
        "## Where the items went",
        "",
        "```mermaid",
        "pie showData",
        '    title Raised items by disposition',
    ]
    for key, label in DISPOSITIONS.items():
        if by_disposition[key]:
            lines.append(f'    "{label}" : {by_disposition[key]}')
    lines += [
        "```",
        "",
        "## Where the items were raised",
        "",
        "```mermaid",
        "pie showData",
        '    title Raised items by source',
    ]
    for key, count in by_source.most_common():
        lines.append(f'    "{SOURCES.get(key, key)}" : {count}')
    lines += ["```", ""]
    for key, label in DISPOSITIONS.items():
        group = [item for item in items if item["disposition"] == key]
        if not group:
            continue
        lines += [
            f"## {label} ({len(group)})",
            "",
            "| ID | Point | Raised by | Source | Where it went |",
            "|---|---|---|---|---|",
        ]
        for item in group:
            lines.append(
                f"| {item['id']} | {cell(item['point'])} | {cell(', '.join(item['raised_by']))} "
                f"| {SOURCES.get(item['source'], item['source'])} | {cell(item['where'])} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Write the page, or with --check report whether it is stale."""
    items = yaml.safe_load(SOURCE.read_text())["items"]
    unknown = {item["disposition"] for item in items} - set(DISPOSITIONS)
    if unknown:
        print(f"Unknown disposition(s) in {SOURCE}: {sorted(unknown)}", file=sys.stderr)
        return 1
    page = render(items)
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != page:
            print(f"{TARGET} is stale; run scripts/render_raised_items.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(page)
    print(f"Wrote {TARGET} ({len(items)} items)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
